import {
  Library,
  FlaskConical,
  Sigma,
  ChartNoAxesCombined,
  CodeXml,
  BrainCircuit,
  Lightbulb,
  Landmark,
  Languages,
  BookOpenText,
  Palette,
  Music2,
  History,
  Amphora,
  Map,
  UsersRound,
  Brain,
  GraduationCap,
  Network,
  Vote,
  Scale,
  ChartSpline,
  WalletCards,
  BriefcaseBusiness,
  Newspaper,
  Globe,
  Atom,
  TestTubeDiagonal,
  Orbit,
  Mountain,
  Dna,
  Leaf,
  Pill,
  Stethoscope,
  HeartPulse,
  Sprout,
  CookingPot,
  Boxes,
  Bot,
  Cpu,
  Zap,
  Building2,
  Plane,
  ShieldCheck,
  Wrench,
  House,
  Bike,
  Compass,
} from 'lucide-react';

const presentations = [
  ['信息与知识', '资料、检索与知识组织', Library],
  ['研究方法', '观察、实验与测量', FlaskConical],
  ['数学', '数量、结构与推理', Sigma],
  ['统计与系统', '数据、决策与模型', ChartNoAxesCombined],
  ['计算机', '编程、软件与网络', CodeXml],
  ['人工智能', '机器学习与认知计算', BrainCircuit],
  ['哲学', '逻辑、思想与伦理', Lightbulb],
  ['宗教与神话', '信仰、传统与故事', Landmark],
  ['语言与文字', '语言、文字与翻译', Languages],
  ['文学', '阅读、写作与叙事', BookOpenText],
  ['艺术与设计', '视觉、设计与工艺', Palette],
  ['音乐与表演', '乐器、舞台与影视', Music2],
  ['历史', '时代、事件与史学', History],
  ['考古与遗产', '文物、遗址与保护', Amphora],
  ['地理与地方', '区域、空间与地方', Map],
  ['人类与民俗', '文化、族群与传统', UsersRound],
  ['心理与行为', '感知、情绪与认知', Brain],
  ['教育与学习', '教学、方法与成长', GraduationCap],
  ['社会与人口', '群体、关系与社会工作', Network],
  ['政治与治理', '制度、政策与公共事务', Vote],
  ['法律与权利', '规则、司法与权利', Scale],
  ['经济', '市场、制度与发展', ChartSpline],
  ['金融与会计', '货币、财务与保险', WalletCards],
  ['管理与商业', '组织、经营与协作', BriefcaseBusiness],
  ['新闻与传播', '媒体、出版与表达', Newspaper],
  ['国际关系', '国际秩序、战争与和平', Globe],
  ['物理', '运动、物质与能量', Atom],
  ['化学', '分子、反应与实验', TestTubeDiagonal],
  ['天文与太空', '星体、宇宙与探索', Orbit],
  ['地球科学', '大地、海洋与气候', Mountain],
  ['生命科学', '生命、遗传与演化', Dna],
  ['生态与环境', '生态、环境与可持续发展', Leaf],
  ['基础医学', '人体、药物与机制', Pill],
  ['临床与康复', '诊疗、护理与康复', Stethoscope],
  ['公共健康', '预防、健康与照护', HeartPulse],
  ['农业与兽医', '种植、养殖与动物', Sprout],
  ['烹饪与饮食', '食材、烹饪与食品', CookingPot],
  ['材料与制造', '工程、材料与工艺', Boxes],
  ['机械与机器人', '机器、运动与工业', Bot],
  ['电子与通信', '电路、通信与控制', Cpu],
  ['能源与资源', '能源、资源与化工', Zap],
  ['建筑与城市', '建筑、土木与规划', Building2],
  ['交通与航天', '运输、物流与航天', Plane],
  ['安全与应急', '风险、灾害与防护', ShieldCheck],
  ['职业与工作', '职业、劳动与专业服务', Wrench],
  ['日常生活', '家庭、生活与个人事务', House],
  ['运动与休闲', '体育、游戏与旅行', Bike],
  ['跨领域探索', '复杂问题与开放议题', Compass],
] as const;

export function domainPresentation(code: string) {
  const number = Number(code.slice(1, 3));
  const entry = code.startsWith('K') ? presentations[number - 1] : undefined;
  return entry
    ? { name: entry[0], description: entry[1], Icon: entry[2] }
    : { name: '交叉索引', description: '用另一种方式寻找主题', Icon: Library };
}

export const featuredDomains = ['K12', 'K17', 'K05', 'K37', 'K29', 'K46'];
